### ISSUE TITLE
V3.2 Roadmap

### ISSUE THREAD

**Issue by Sam-Neale** [VACenter/VACenter#79]
# Summary

VACenter 3.2 will focus on adding some new features to the crew center for added functionality. The update will also add the new updater and performance benefits. 

# Feature List

:page_facing_up: In Planning
:man_technologist: In Progress
:man_judge:  Under Review
:white_check_mark: Complete
:x: Cancelled

| Status | Feature            | Type          | Issue | Assignee    |
| ------ | ------------------ | ------------- | ----- | ----------- |
| :x: |New Updater| Overhaul | #72 | @Sam-Neale |
| :white_check_mark: |Stats Page overhaul| Overhaul | #66 #67 | @Sam-Neale |
| :white_check_mark: |Move 'add' buttons to top of page| Design Enhancement | #69 | @Sam-Neale |
| :white_check_mark: |Implement searches (for tables) everywhere| Design Enhancement | #73 | @Sam-Neale |
| :white_check_mark: |Applications & User Page redo| Feature & Overhaul | #74 | @Sam-Neale |
| :x: |Updated Settings page| Overhaul | #75 | @Sam-Neale |
| :white_check_mark: |Codeshare| Overhaul | #76 | @Sam-Neale |
| :white_check_mark: |Ranks| Overhaul | #77 | @Sam-Neale |
| :white_check_mark: |API Enhancements|Feature | #78 | @Sam-Neale |
| :white_check_mark: | Multipliers | Feature | #91 | @Sam-Neale |

# Things to Test

- [x] Columns for tables are correct
- [x] Screen size
- [x] Button colours
- [x] Operators are working (Lots of issues that weren't present until PR????)
- [x] New API features
- [ ] Malicious Inputs

**Comment by Sam-Neale** [comment]
Forgot this was open whoops
